print("Student Grade Calculator")
score1 = input("Enter score 1: ")
score1 = int(score1)
score2 = input("Enter score 2: ")
score2 = int(score2)
score3 = input("Enter score 3: ")
score3 = int(score3)
score4 = input("Enter score 4: ")
score4 = int(score4)
score5 = input(Enter score 5: ")
score5 = int(score5)
average = (score1 + score2 + score3 + score4 +score5) /5
